### ISSUE TITLE
Wrong schema format error for google enhanced-ecommerce

### ISSUE THREAD

**Issue by jamienz** [snowplow-incubator/snowplow-js-analytics-sdk#12]
When an event contains a reference to an enhanced-ecommerce schema, e.g. `iglu:com.google.analytics.enhanced-ecommerce/productFieldObject/jsonschema/1-0-0` I get an error:

TypeError: Wrong schema format.

This is because the regex in src/types.ts used to match schema URIs doesn't allow for hyphens, i.e.
`const SCHEMA_PATTERN = new RegExp(".+:([a-zA-Z0-9_\.]+)/([a-zA-Z0-9_\-]+)/[^/]+/(.*)");`
it needs to be changed to:
`const SCHEMA_PATTERN = new RegExp(".+:([a-zA-Z0-9_\.\-]+)/([a-zA-Z0-9_\-]+)/[^/]+/(.*)");`

**Comment by StephenHonor** [comment]
@BenFradet

**Comment by BenFradet** [comment]
hey @StephenHonor , I don't work at snowplow analytics anymore, I'd suggest mentioning someone else.

**Comment by StephenHonor** [comment]
Ahh, well that explains a few things. I wondered why everything had slowed down release wise! Sad to see you've left but hope you've gone somewhere awesome! @BenFradet

**Comment by StephenHonor** [comment]
@chuwy Not sure who the best person to look at this is? I don't suppose you can point me in the right direction?

**Comment by chuwy** [comment]
Hi @StephenHonor! If you submit a PR (would be better to base it on top of [this PR](https://github.com/snowplow-incubator/snowplow-js-analytics-sdk/pull/14)) with the fix it will definitely be included in the next release. I cannot promise you though when that release will be available - hopefully early in January.
