### ISSUE TITLE
Fix refr_dvce_tstamp field naming

### ISSUE THREAD

**Issue by rzats** [snowplow-incubator/snowplow-js-analytics-sdk#13]
The `refr_dvce_tstamp` field is referred to as `refr_device_tstamp` in this and other [Analytics SDKs](https://github.com/snowplow/snowplow/wiki/Snowplow-Analytics-SDK), which does not match its name in the [canonical event model](https://github.com/snowplow/snowplow/wiki/canonical-event-model#221-web-specific-fields).

**Comment by chuwy** [comment]
JS SDK: https://github.com/snowplow-incubator/snowplow-js-analytics-sdk/issues/13
