### ISSUE TITLE
Context column name suffixes (eg. "_1_0_0") are incorrectly rounded down ("_1") when TSV is converted to JSON

### ISSUE THREAD

**Issue by stefl** [snowplow-incubator/snowplow-js-analytics-sdk#29]
I'm using this library in a cloud function in GCP to selectively push analytics data into a separate BigQuery instance.

My schema for the BigQuery table I have for the standard Snowplow GCP pipeline ends up with columns that include a version number. Eg. "contexts_com_snowplowanalytics_snowplow_ua_parser_context_1_0_0".

When I use the SDK to convert from TSV to JSON to write into a BigQuery table with the same schema as my main table, I get a failure because this (and any other table with a version number suffix, all of which are 1.0.0) becomes "contexts_com_snowplowanalytics_snowplow_ua_parser_context_1" without the "_0_0".

This implies to me there's a bug with the way that the SDK handles floats for these versions, and because it is "1.0.0", this gets rounded to an integer "1" when creating the JSON object keys.

Because there is no column "contexts_com_snowplowanalytics_snowplow_ua_parser_context_1" when I attempt to write to BigQuery, the write fails.

**Comment by chuwy** [comment]
Hi @stef! No, there's no bug. Technically all columns in BQ should also have only`_1` suffix, it's what we call MODEL in SchemaVer stanard and means that everything withing that MODEL is backward compatible and thus could be inserted into the same column and ther's no breaking difference between `1-0-0` and `1-1-1`, every query working with latter one should handle former one as well.

However, our BigQuery Loader does not support this kind of migrations yet. We're planning to add it, but no ETA yet.

Closing this as a non-issue.
